function timeToMinutes(v) {
    if (!v)
        return null;

    v = String(v).trim();

    if (v === "2400")
        return 1440;

    v = v.padStart(4, "0");

    const h =
        Number(v.slice(0, 2));

    const m =
        Number(v.slice(2, 4));

    if (
        !Number.isFinite(h) ||
        !Number.isFinite(m)) {
        return null;
    }

    return h * 60 + m;
}

function utcMinutesNow(date) {
    return (
        date.getUTCHours() * 60 +
        date.getUTCMinutes()
    );
}

function timeMatches(item, now) {

    const n =
        utcMinutesNow(now);

    const s =
        timeToMinutes(item.start);

    const e =
        timeToMinutes(item.end);

    if (
        s === null ||
        e === null) {
        return false;
    }

    /*
     * Same start/end means 24 h.
     */

    if (s === e)
        return true;

    /*
     * Normal interval.
     */

    if (s < e)
        return n >= s && n < e;

    /*
     * Interval crossing midnight.
     */

    return n >= s || n < e;
}

function formatSite(item) {
    return (
        item.txSite ||
        item.txCode ||
        item.type ||
        "—"
    );
}

function jsonResponse(
    payload,
    status = 200) {

    return new Response(
        JSON.stringify(payload),
        {
            status: status,

            headers: {
                "content-type":
                    "application/json; charset=utf-8",

                "cache-control":
                    "public, max-age=30, s-maxage=60",

                "access-control-allow-origin":
                    "*"
            }
        });
}

export async function onRequestGet(context) {

    const url =
        new URL(
            context.request.url);

    const khz =
        Number(
            url.searchParams.get("khz"));

    /*
     * VadelmaRX currently uses exact
     * frequency matching only.
     */

    if (
        !Number.isFinite(khz) ||
        khz <= 0) {

        return jsonResponse(
            {
                error:
                    "invalid frequency",

                example:
                    "/api/frequency?khz=9685"
            },
            400);
    }

    /*
     * Frequency files are generated by
     * tools/import.js from current EiBi data.
     */

    const origin =
        url.origin;

    const frequencyUrl =
        origin +
        "/data/frequency/" +
        encodeURIComponent(khz) +
        ".json";

    let frequencyData;

    try {

        const response =
            await fetch(
                frequencyUrl,
                {
                    cf: {
                        cacheTtl: 300,
                        cacheEverything: true
                    }
                });

        /*
         * Missing file simply means that EiBi
         * has no schedules for this frequency.
         */

        if (response.status === 404) {

            return jsonResponse({
                version: 2,
                updated:
                    new Date().toISOString(),

                frequency_khz:
                    khz,

                tolerance_khz:
                    0,

                count:
                    0,

                matches:
                    []
            });
        }

        if (!response.ok) {

            return jsonResponse(
                {
                    error:
                        "frequency source unavailable",

                    status:
                        response.status
                },
                503);
        }

        frequencyData =
            await response.json();

    } catch (error) {

        return jsonResponse(
            {
                error:
                    "frequency source unavailable"
            },
            503);
    }

    const schedules =
        Array.isArray(
            frequencyData?.schedules)
            ? frequencyData.schedules
            : [];

    const now =
        new Date();

    /*
     * Only a handful of schedules are examined
     * here instead of the complete schedules.json.
     */

    const matches =
        schedules

        .filter(
            item =>
                timeMatches(
                    item,
                    now))

        .map(
            item => ({
                frequency:
                    Number(item.freq),

                offset_khz:
                    Number(item.freq) - khz,

                station:
                    item.station ||
                    "Unknown station",

                country:
                    item.country || "",

                language:
                    item.language || "",

                target:
                    item.target || "",

                start:
                    String(
                        item.start || ""),

                end:
                    String(
                        item.end || ""),

                days:
                    item.days || "",

                days_label:
                    item.daysLabel || "",

                site:
                    formatSite(item),

                tx_country:
                    item.txCountry || "",

                tx_lat:
                    item.txLat ?? null,

                tx_lon:
                    item.txLon ?? null,

                band:
                    item.band || "",

                source:
                    item.source || ""
            }))

        .sort(
            (a, b) =>
                a.frequency -
                b.frequency);

    return jsonResponse({
        version:
            2,

        updated:
            now.toISOString(),

        frequency_khz:
            khz,

        tolerance_khz:
            0,

        count:
            matches.length,

        matches:
            matches
    });
}